version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD:-Secret_ContextStore99!}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9201:9200"
      - "9601:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - opensearch
      - redis
    networks:
      - app-network

volumes:
  opensearch-data:
  redis-data:

networks:
  app-network:
    driver: bridge
